include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - third_party/**
    - build/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    unnecessary_underscores: false
    prefer_initializing_formals: false
    use_null_aware_elements: false
